sudo: required
services:
  - docker

before_install:
  - docker build -t allguitars/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true allguitars/docker-react yarn test
  

# Additionally, you may want to set the following property if your travis build fails with “rakefile not found” by adding to the top of your .travis.yml file:

# language: generic 